// Generated by CoffeeScript 1.6.1
(function() {

  (function($) {
    return $('.off-canvas-icon').on('click', function() {
      var $menu, $wrapper;
      $menu = $('.off-canvas');
      $wrapper = $('.wrapper');
      if ($menu.hasClass('open')) {
        $menu.removeClass('open');
        return $wrapper.removeClass('off');
      } else {
        $menu.addClass('open');
        return $wrapper.addClass('off');
      }
    });
  })(jQuery);

}).call(this);
